/* liblouisutdml Braille Transcription Library

   This file may contain code borrowed from the Linux screenreader
   BRLTTY, copyright (C) 1999-2006 by
   the BRLTTY Team

   Copyright (C) 2004, 2005, 2006
   ViewPlus Technologies, Inc. www.viewplus.com
   and
  Abilitiessoft, Inc. www.abilitiessoft.com
   All rights reserved

   This file is free software; you can redistribute it and/or modify it
   under the terms of the Lesser or Library GNU General Public License 
   as published by the
   Free Software Foundation; either version 3, or (at your option) any
   later version.

   This file is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
   Library GNU General Public License for more details.

   You should have received a copy of the Library GNU General Public 
   License along with this program; see the file COPYING.  If not, write to
   the Free Software Foundation, 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.

   Maintained by John J. Boyer john.boyer@abilitiessoft.com
   */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int
main (void)
{
static const char *makefileStub[] = {
"# Make liblouisutdml.dll and liblouisutdml.lib",
"# Make file2brl.exe",
" ",
"# This file was generated by make_makefile.exe"
"# Do not edit this file. Change configure.msvc.",
"# Then run"
"# nmake /f Make_makefile.msvc"
" ",
"!include configure.msvc",
"!include $(LIBLOUIS_SRC_PATH)\..\windows\configure.msvc",
"SRCDIR = ..\liblouisutdml",
"JAVA_BINDINGS_SRC_PATH = ..\java",
"CC = cl.exe",,
"CFLAGS =  /nologo /Ox /W1 /c",
"HEADERS = $(SRCDIR)\louisutdml.h $(SRCDIR)\liblouisutdml.h liblouisutdml.def include\liblouisutdml.h include\config.h",
"LINK = link.exe",
"DLLFLAGS = /dll /nologo /DEF:liblouisutdml.def $(OBJ) /OUT:liblouisutdml.dll",
"LIB = lib.exe",
"LIBFLAGS = /nologo",
"OBJ = ",
"!if \"$(UCS)\" == \"2\"",
"CFLAGS = $(CFLAGS) /DWIDECHAR_TYPE=\"unsigned short int\"",
"CFLAGS = $(CFLAGS) /DUNICODEBITS=16",
"!else",
"CFLAGS = $(CFLAGS) /DWIDECHAR_TYPE=\"unsigned int\"",
"CFLAGS = $(CFLAGS) /DUNICODEBITS=32",
"!endif",
" ",
"all: liblouisutdml.dll ..\tools\file2brl.c",
"    $(CC) /Ox /w1 /nologo ..\tools\file2brl.c /out:file2brl.exe",
"liblouisutdml.dll: liblouisutdml.lib liblouisutdml.def",
"    $(LINK)  $(DLLFLAGS)  /libpath:$(LIBPATH)",
"liblouisutdml.lib: $(OBJ) libxml2.dll",
"    $(LIB) $(LIBFLAGS) $(OBJ) /out:liblouisutdml.lib",
NULL
}

  FILE *makefile_am;
  FILE *configure_ac;
  FILE *mkefile_msvc;
  char inbuf[1024];
  char *curchar;
  int ch;
  int ignoreLine = 1;
  char *name;
  int nameLength;
  int k;
  if ((makefile_am = fopen ("..\liblouisutdml\Makefile.am", "r")) == NULL)
    {
      fprintf (stderr, "Cannot open Makefile.am.\n");
      exit (1);
    }
if ((configure_ac = fopen ("..\configure.ac", "r") == NULL)
{
fprintf (stderr, "Cannot open configure.ac.\n");
exit (1);
}
  if ((makefile_msvc = fopen ("Makefile.msvc", "w")) == NULL)
    {
      fprintf (stderr, "Cannot open Makefile.msvc.\n");
      exit (1);
    }
  while ((fgets (inbuf, sizeof (inbuf), makefile_am)))
    {
      curchar = inbuf;
      while ((ch = *curchar++) <= 32 && ch != 0);
  if (ch == '/')
continue;
      if (ignoreLine)
	{
	  if (ch == '{')
	    ignoreLine = 0;
	  continue;
	}
      if (ch == '}')
	break;
      name = curchar - 1;
      while ((ch = *curchar++) > 32 && ch != ',' && ch != '=');
      nameLength = curchar - name - 1;
      name[nameLength] = 0;
    }
fclose (makefile_am);

  while ((fgets (inbuf, sizeof (inbuf), configure_ac)))
    {
      curchar = inbuf;
      while ((ch = *curchar++) <= 32 && ch != 0);
  if (ch == '/')
continue;
      if (ignoreLine)
	{
	  if (ch == '{')
	    ignoreLine = 0;
	  continue;
	}
      if (ch == '}')
	break;
      name = curchar - 1;
      while ((ch = *curchar++) > 32 && ch != ',' && ch != '=');
      nameLength = curchar - name - 1;
      name[nameLength] = 0;
    }
fclose (configure_ac);

for (k = 0; makefileStub[k] != NULL; k++)
{
fprintf (makefile_msvc, "%s\n", makefileStub[k]);
}
  fclose (makefile_msvc);
  return 0;
}