/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __org_brailleblaster_jlouislibs_Jliblouisutdml__
#define __org_brailleblaster_jlouislibs_Jliblouisutdml__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jstring JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1version (JNIEnv *env, jobject);
JNIEXPORT jboolean JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1translateString (JNIEnv *env, jobject, jstring, jbyteArray, jbyteArray, jintArray, jstring, jstring, jint);
JNIEXPORT jboolean JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1backTranslateString (JNIEnv *env, jobject, jstring, jbyteArray, jbyteArray, jintArray, jstring, jstring, jint);
JNIEXPORT jboolean JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1translateFile (JNIEnv *env, jobject, jstring, jstring, jstring, jstring, jstring, jint);
JNIEXPORT jboolean JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1translateTextFile (JNIEnv *env, jobject, jstring, jstring, jstring, jstring, jstring, jint);
JNIEXPORT jboolean JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1backTranslateFile (JNIEnv *env, jobject, jstring, jstring, jstring, jstring, jstring, jint);
JNIEXPORT void JNICALL Java_org_brailleblaster_jlouislibs_Jliblouisutdml_lbu_1free (JNIEnv *env, jobject);
#undef org_brailleblaster_jlouislibs_Jliblouisutdml_dontInit
#define org_brailleblaster_jlouislibs_Jliblouisutdml_dontInit 1L
#undef org_brailleblaster_jlouislibs_Jliblouisutdml_htmlDoc
#define org_brailleblaster_jlouislibs_Jliblouisutdml_htmlDoc 2L

#ifdef __cplusplus
}
#endif

#endif /* __org_brailleblaster_jlouislibs_Jliblouisutdml__ */
