SUBDIRS = \
	arithmetic.test \
	alphabets.test \
	boundaries.test \
	brackets.test \
	extensions.test \
	algebraic_fraction.test \
	functions.test \
	functions_analysis.test \
	marks_geometry.test \
	geometry.test \
	sets_logic.test \
	layouts.test \
	fraction.test \
	formatting.test \
	multiscripts.test \
	operators.test \
	root.test \
	scripts.test \
	variants.test \
	regressions.test \
	mathml_layouts.test

EXTRA_DIST = \
	README \
	liblouisutdml.ini \
	styles.cfg
