#!/usr/bin/perl
use strict;
use warnings;

my $start = 0;

print "/* Do not edit this file. It is automatically generated by ", $0, " */\n";
print "#ifndef __SEM_NAMES_h\n";
print "#define __SEM_NAMES_h\n";
print "static const char *semNames[] = {\n";
 
while (<>) {
    # only look at the lines between the curly brackets
    if (/{/ .. /}/) { 
	chomp;
	next if /[{}]/; # ignore the lines with curly brackets
	next if /^\s*\/\*/; # ignore comments
	s/^\s+([A-Za-z0-9_]+).*/$1/g; # extract the name
	print "  \"", $_, "\",\n";
    }
}

print "NULL\n";
print "};\n";
print "#endif /*__SEM_NAMES_H*/\n";
