/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_liblouis_Jliblouisutdml */

#ifndef _Included_org_liblouis_Jliblouisutdml
#define _Included_org_liblouis_Jliblouisutdml
#ifdef __cplusplus
extern "C" {
#endif
#undef org_liblouis_Jliblouisutdml_noContractions
#define org_liblouis_Jliblouisutdml_noContractions 1L
#undef org_liblouis_Jliblouisutdml_compbrlAtCursor
#define org_liblouis_Jliblouisutdml_compbrlAtCursor 2L
#undef org_liblouis_Jliblouisutdml_dotsIO
#define org_liblouis_Jliblouisutdml_dotsIO 4L
#undef org_liblouis_Jliblouisutdml_comp8Dots
#define org_liblouis_Jliblouisutdml_comp8Dots 8L
#undef org_liblouis_Jliblouisutdml_pass1Only
#define org_liblouis_Jliblouisutdml_pass1Only 16L
#undef org_liblouis_Jliblouisutdml_compbrlLeftCursor
#define org_liblouis_Jliblouisutdml_compbrlLeftCursor 32L
#undef org_liblouis_Jliblouisutdml_otherTrans
#define org_liblouis_Jliblouisutdml_otherTrans 64L
#undef org_liblouis_Jliblouisutdml_ucBrl
#define org_liblouis_Jliblouisutdml_ucBrl 128L
#undef org_liblouis_Jliblouisutdml_dontInit
#define org_liblouis_Jliblouisutdml_dontInit 1073741824L
#undef org_liblouis_Jliblouisutdml_htmlDoc
#define org_liblouis_Jliblouisutdml_htmlDoc 536870912L
/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_liblouis_Jliblouisutdml_version
  (JNIEnv *, jobject);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    translateString
 * Signature: (Ljava/lang/String;[B[B[ILjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_liblouis_Jliblouisutdml_translateString
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jintArray, jstring, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    backTranslateString
 * Signature: (Ljava/lang/String;[B[B[ILjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_liblouis_Jliblouisutdml_backTranslateString
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jintArray, jstring, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    translateFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_liblouis_Jliblouisutdml_translateFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    translateTextFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_liblouis_Jliblouisutdml_translateTextFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    backTranslateFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_liblouis_Jliblouisutdml_backTranslateFile
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    charToDots
 * Signature: (Ljava/lang/String;[B[BLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_liblouis_Jliblouisutdml_charToDots
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    dotsToChar
 * Signature: (Ljava/lang/String;[B[BLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_liblouis_Jliblouisutdml_dotsToChar
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    checkTable
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_liblouis_Jliblouisutdml_checkTable
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    compileString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_liblouis_Jliblouisutdml_compileString
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    setDataPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_liblouis_Jliblouisutdml_setDataPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    charSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_liblouis_Jliblouisutdml_charSize
  (JNIEnv *, jobject);

/*
 * Class:     org_liblouis_Jliblouisutdml
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liblouis_Jliblouisutdml_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
